import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'

export default function Home() {
	const router = useRouter()
	const { data: session } = useSession()

	useEffect(() => {
		if (!session) router.push('/login')
	}, [router, session])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					<p>Get started</p>
				</div>
			</main>
		</>
	)
}
